name: Discover Versions

on:
  workflow_dispatch:
    inputs:
      force:
        required: false
        type: boolean
  schedule:
    - cron: '0 * * * *'

jobs:
  discover:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Nixpacks
        run: curl -sSL https://nixpacks.com/install.sh | bash

      - name: Install Packages
        run: bun i

      - name: Run Discover Versions
        run: bun start ${{ github.event.inputs.force == 'true' && '--force' || '' }}
        working-directory: 'scripts/check-versions'

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Add new container versions
          branch: update-container-versions
          delete-branch: true
          title: 'chore: Update container versions'
          body: |
            This PR updates the container versions used in the repository.
            This is an automated PR generated by Metorial MCP Containers.
          committer: metorial[bot] <120314019+metorial@users.noreply.github.com>
          author: metorial[bot] <120314019+metorial@users.noreply.github.com>

      - name: Enable Auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Output PR Info
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
